"""initial database schema

Revision ID: d4c821fea9fa
Revises: 
Create Date: 2026-10-04 13:03:41.035538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c821fea9fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('item_seq', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=500), nullable=False),
    sa.Column('entp_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('item_seq')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Seoul', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_medicines',
    sa.Column('user_medicine_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medicine_item_seq', sa.String(length=50), nullable=False),
    sa.Column('registration_source', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("registration_source IN ('search', 'image_recognition')", name='ck_user_medicine_registration_source'),
    sa.ForeignKeyConstraint(['medicine_item_seq'], ['medicines.item_seq'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_medicine_id'),
    sa.UniqueConstraint('user_id', 'medicine_item_seq', name='uq_user_medicine')
    )
    with op.batch_alter_table('user_medicines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_medicines_medicine_item_seq'), ['medicine_item_seq'], unique=False)

    op.create_table('medication_schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('user_medicine_id', sa.Integer(), nullable=False),
    sa.Column('intake_timing', sa.String(length=50), nullable=False),
    sa.Column('dose_amount_text', sa.String(length=100), nullable=False),
    sa.Column('dose_unit_text', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('monday', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('tuesday', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('wednesday', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('thursday', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('friday', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('saturday', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('sunday', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_medication_schedule_date_range'),
    sa.CheckConstraint('monday OR tuesday OR wednesday OR thursday OR friday OR saturday OR sunday', name='ck_medication_schedule_weekday'),
    sa.ForeignKeyConstraint(['user_medicine_id'], ['user_medicines.user_medicine_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    with op.batch_alter_table('medication_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_schedules_user_medicine_id'), ['user_medicine_id'], unique=False)

    op.create_table('medication_times',
    sa.Column('medication_time_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.schedule_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medication_time_id'),
    sa.UniqueConstraint('schedule_id', 'time_of_day', name='uq_medication_schedule_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medication_times')
    with op.batch_alter_table('medication_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_schedules_user_medicine_id'))

    op.drop_table('medication_schedules')
    with op.batch_alter_table('user_medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_medicines_medicine_item_seq'))

    op.drop_table('user_medicines')
    op.drop_table('users')
    op.drop_table('medicines')
    # ### end Alembic commands ###
